/*
 * ReglaControlIFrame.java
 *
 * Created on 04/08/2009, 17:09:11
 */
package edu.utn.frm.ui.control;

import edu.utn.frm.action.exception.ReporteException;
import edu.utn.frm.action.reglacontrol.ReglaControlAbm;
import edu.utn.frm.dao.generic.ValidateException;
import edu.utn.frm.entities.regla.MomentoRemontaje;
import edu.utn.frm.entities.regla.ReglaControl;
import edu.utn.frm.entities.regla.ReglaControlNivel;
import edu.utn.frm.entities.regla.ReglaControlRemontaje;
import edu.utn.frm.entities.regla.ReglaControlTemperatura;
import edu.utn.frm.entities.regla.RemontajeDia;
import edu.utn.frm.ui.IconManager;
import edu.utn.frm.ui.utils.GenericComboBoxModel;
import javax.swing.JOptionPane;


import edu.utn.frm.ui.utils.GenericTableModel;
import edu.utn.frm.ui.utils.Utiles;
import java.util.List;

/**
 *
 * @author Proyecto
 */
public class ReglaControlIFrame extends javax.swing.JInternalFrame {

    private GenericTableModel<ReglaControl> model = new GenericTableModel<ReglaControl>(
            new String[]{"Código", "Descripción"},
            new String[]{"codigo", "descripcion"});
    private ReglaControlAbm gestorAbm = new ReglaControlAbm();
    private GenericComboBoxModel<ReglaControlTemperatura> modelTemperatura = new GenericComboBoxModel<ReglaControlTemperatura>(
            buscarTodosReglaTemperatura(), "descripcion");
    private GenericComboBoxModel<ReglaControlNivel> modelNivel = new GenericComboBoxModel<ReglaControlNivel>(
            buscarTodosReglaNivel(), "descripcion");
    private GenericComboBoxModel<ReglaControlRemontaje> modelRemontaje = new GenericComboBoxModel<ReglaControlRemontaje>(
            buscarTodosReglaRemontaje(), "descripcion");
    private GenericTableModel<RemontajeDia> modelRemontajeDia = new GenericTableModel<RemontajeDia>(
            new String[]{"Nombre"},
            new String[]{"nombre"});
    private GenericTableModel<MomentoRemontaje> modelMomentoRemontaje = new GenericTableModel<MomentoRemontaje>(
            new String[]{"Hora Inicio", "Hora Fin", "Duración"},
            new String[]{"horaInicioString", "horaFinString", "duracion"});

    /** Creates new form FincaIFrame */
    public ReglaControlIFrame() {
        initComponents();
        habilitarPanelDatos(false);
        model.setRows(gestorAbm.buscar());
        tablaRemontajeDia.setModel(modelRemontajeDia);
        tablaMomentoRemontaje.setModel(modelMomentoRemontaje);
        this.setFrameIcon(IconManager.getInstance().getFrameIcon());
        //sPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(" Giros Comerciales [" + model.getRowCount() + "] "));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        datosDialog = new javax.swing.JDialog();
        datosPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        codigoText = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        descripcionText = new javax.swing.JTextField();
        limpiarDatosEntityButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        temperaturaComboBox = new javax.swing.JComboBox();
        verTemperaturaButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        nivelComboBox = new javax.swing.JComboBox();
        verNivelButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        remontajeComboBox = new javax.swing.JComboBox();
        verRemontajeButton = new javax.swing.JButton();
        cerrarButton = new javax.swing.JButton();
        guardarButton = new javax.swing.JButton();
        eliminarButton = new javax.swing.JButton();
        datosDialogTemperatura = new javax.swing.JDialog();
        datosPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        codigoTemperaturaText = new javax.swing.JTextField();
        temperaturaMinimaText = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        descripcionTemperaturaText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        temperaturaMaximaText = new javax.swing.JTextField();
        temperaturaToleranciaText = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cerrarTemperaturaButton = new javax.swing.JButton();
        datosDialogNivel = new javax.swing.JDialog();
        datosPanel5 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        codigoNivelText = new javax.swing.JTextField();
        nivelMinimoAzucarText = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        descripcionNivelText = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        nivelMaximoLitrosText = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        cerrarNivelButton = new javax.swing.JButton();
        datosDialogRemontaje = new javax.swing.JDialog();
        datosPanel = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        codigoRemontajeText = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        descripcionRemontajeText = new javax.swing.JTextField();
        sPanel1 = new javax.swing.JScrollPane();
        tablaRemontajeDia = new javax.swing.JTable();
        verRemontajeDiaButton = new javax.swing.JButton();
        cerrarRemontajeButton = new javax.swing.JButton();
        datosDialogRemontajeDia = new javax.swing.JDialog();
        datosPanel3 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        nombreRemontajeDiaText = new javax.swing.JTextField();
        sPanel2 = new javax.swing.JScrollPane();
        tablaMomentoRemontaje = new javax.swing.JTable();
        cerrarRemontajeDiaButton = new javax.swing.JButton();
        sPanel = new javax.swing.JScrollPane();
        buscarTabla = new javax.swing.JTable();
        salirButton = new javax.swing.JButton();
        buscarCodigoText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        buscarButton = new javax.swing.JButton();
        limpiarBuscadorButton = new javax.swing.JButton();
        nuevoButton = new javax.swing.JButton();
        editarButton = new javax.swing.JButton();
        buscarDescripcionText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        copiarButton = new javax.swing.JButton();
        generarInformeButton = new javax.swing.JButton();

        datosDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        datosDialog.setTitle("Regla de Control");
        datosDialog.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        datosDialog.setLocationByPlatform(true);
        datosDialog.setMinimumSize(new java.awt.Dimension(540, 420));
        datosDialog.setModal(true);
        datosDialog.setName("datosDialog"); // NOI18N
        datosDialog.setResizable(false);
        datosDialog.addWindowListener(new java.awt.event.WindowAdapter() {

            public void windowClosed(java.awt.event.WindowEvent evt) {
                datosDialog_windowClosed(evt);
            }
        });

        datosPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Regla de Control"));
        datosPanel1.setName("datosPanel1"); // NOI18N

        jLabel2.setFont(jLabel2.getFont().deriveFont(jLabel2.getFont().getStyle() & ~java.awt.Font.BOLD));
        jLabel2.setText("Código:");
        jLabel2.setName("jLabel2"); // NOI18N

        codigoText.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        codigoText.setName("txtTPatente"); // NOI18N

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${entity.codigo}"), codigoText, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jLabel7.setText("Descripción:");
        jLabel7.setName("jLabel7"); // NOI18N

        descripcionText.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        descripcionText.setName("txtTMarca"); // NOI18N

        limpiarDatosEntityButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/utn/frm/ui/resources/image/limpiar.png"))); // NOI18N
        limpiarDatosEntityButton.setText("Limpiar");
        limpiarDatosEntityButton.setName("limpiarDatosEntityButton"); // NOI18N
        limpiarDatosEntityButton.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarDatosEntityButtonActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Regla de Control de Temperatura"));
        jPanel1.setName("jPanel1"); // NOI18N

        temperaturaComboBox.setModel(modelTemperatura);
        temperaturaComboBox.setName("temperaturaComboBox"); // NOI18N
        temperaturaComboBox.addItemListener(new java.awt.event.ItemListener() {

            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                temperaturaComboBoxItemStateChanged(evt);
            }
        });

        verTemperaturaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/utn/frm/ui/resources/image/ver.png"))); // NOI18N
        verTemperaturaButton.setText("Ver");
        verTemperaturaButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        verTemperaturaButton.setEnabled(false);
        verTemperaturaButton.setName("verTemperaturaButton"); // NOI18N
        verTemperaturaButton.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verTemperaturaButton(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel1Layout.createSequentialGroup().addContainerGap().addComponent(temperaturaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(verTemperaturaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE).addContainerGap(161, Short.MAX_VALUE)));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup().addContainerGap(16, Short.MAX_VALUE).addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(temperaturaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(verTemperaturaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)).addContainerGap()));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Regla de Control de Nivel"));
        jPanel2.setName("jPanel2"); // NOI18N

        nivelComboBox.setModel(modelTemperatura);
        nivelComboBox.setName("nivelComboBox"); // NOI18N
        nivelComboBox.setModel(modelNivel);
        nivelComboBox.addItemListener(new java.awt.event.ItemListener() {

            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                nivelComboBoxItemStateChanged(evt);
            }
        });

        verNivelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/utn/frm/ui/resources/image/ver.png"))); // NOI18N
        verNivelButton.setText("Ver");
        verNivelButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        verNivelButton.setEnabled(false);
        verNivelButton.setName("verNivelButton"); // NOI18N
        verNivelButton.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verNivelButton(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel2Layout.createSequentialGroup().addContainerGap().addComponent(nivelComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(verNivelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE).addContainerGap(161, Short.MAX_VALUE)));
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 49, Short.MAX_VALUE).addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup().addContainerGap(13, Short.MAX_VALUE).addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(nivelComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(verNivelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)).addContainerGap()));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Regla de Control de Remontaje"));
        jPanel3.setName("jPanel3"); // NOI18N

        remontajeComboBox.setModel(modelTemperatura);
        remontajeComboBox.setName("remontajeComboBox"); // NOI18N
        remontajeComboBox.setModel(modelRemontaje);
        remontajeComboBox.addItemListener(new java.awt.event.ItemListener() {

            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                remontajeComboBoxItemStateChanged(evt);
            }
        });

        verRemontajeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/utn/frm/ui/resources/image/ver.png"))); // NOI18N
        verRemontajeButton.setText("Ver");
        verRemontajeButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        verRemontajeButton.setEnabled(false);
        verRemontajeButton.setName("verRemontajeButton"); // NOI18N
        verRemontajeButton.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verRemontajeButton(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel3Layout.createSequentialGroup().addContainerGap().addComponent(remontajeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(verRemontajeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE).addContainerGap(161, Short.MAX_VALUE)));
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 49, Short.MAX_VALUE).addGap(0, 49, Short.MAX_VALUE).addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup().addContainerGap(13, Short.MAX_VALUE).addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(remontajeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(verRemontajeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)).addContainerGap()));

        javax.swing.GroupLayout datosPanel1Layout = new javax.swing.GroupLayout(datosPanel1);
        datosPanel1.setLayout(datosPanel1Layout);
        datosPanel1Layout.setHorizontalGroup(
                datosPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(datosPanel1Layout.createSequentialGroup().addContainerGap().addGroup(datosPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addGroup(datosPanel1Layout.createSequentialGroup().addComponent(jLabel2).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(codigoText, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jLabel7).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(descripcionText, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(limpiarDatosEntityButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)).addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)).addContainerGap()));
        datosPanel1Layout.setVerticalGroup(
                datosPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(datosPanel1Layout.createSequentialGroup().addContainerGap().addGroup(datosPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(limpiarDatosEntityButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(codigoText, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jLabel2).addComponent(jLabel7).addComponent(descripcionText, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)).addGap(18, 18, 18).addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        cerrarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/utn/frm/ui/resources/image/cerrar.png"))); // NOI18N
        cerrarButton.setText("Cerrar");
        cerrarButton.setName("cerrarButton"); // NOI18N
        cerrarButton.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarButtonActionPerformed(evt);
            }
        });

        guardarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/utn/frm/ui/resources/image/guardar.png"))); // NOI18N
        guardarButton.setText("Guardar");
        guardarButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        guardarButton.setName("guardarButton"); // NOI18N
        guardarButton.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardar(evt);
            }
        });

        eliminarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/utn/frm/ui/resources/image/eliminar.png"))); // NOI18N
        eliminarButton.setText("Eliminar");
        eliminarButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        eliminarButton.setName("eliminarButton"); // NOI18N
        eliminarButton.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminar(evt);
            }
        });

        javax.swing.GroupLayout datosDialogLayout = new javax.swing.GroupLayout(datosDialog.getContentPane());
        datosDialog.getContentPane().setLayout(datosDialogLayout);
        datosDialogLayout.setHorizontalGroup(
                datosDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(javax.swing.GroupLayout.Alignment.TRAILING, datosDialogLayout.createSequentialGroup().addContainerGap().addGroup(datosDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addComponent(datosPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addGroup(datosDialogLayout.createSequentialGroup().addComponent(guardarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(eliminarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 241, Short.MAX_VALUE).addComponent(cerrarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))).addContainerGap()));
        datosDialogLayout.setVerticalGroup(
                datosDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(javax.swing.GroupLayout.Alignment.TRAILING, datosDialogLayout.createSequentialGroup().addContainerGap().addComponent(datosPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addGroup(datosDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(cerrarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(eliminarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(guardarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)).addContainerGap()));

        datosDialogTemperatura.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        datosDialogTemperatura.setTitle("Regla  de Control de Temperatura");
        datosDialogTemperatura.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        datosDialogTemperatura.setLocationByPlatform(true);
        datosDialogTemperatura.setMinimumSize(new java.awt.Dimension(432, 250));
        datosDialogTemperatura.setModal(true);
        datosDialogTemperatura.setName("datosDialogTemperatura"); // NOI18N
        datosDialogTemperatura.setResizable(false);
        datosDialogTemperatura.addWindowListener(new java.awt.event.WindowAdapter() {

            public void windowClosed(java.awt.event.WindowEvent evt) {
                datosDialogTemperatura_windowClosed(evt);
            }
        });

        datosPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Regla de Control de Temperatura"));
        datosPanel2.setName("datosPanel2"); // NOI18N

        jLabel3.setFont(jLabel3.getFont().deriveFont(jLabel3.getFont().getStyle() & ~java.awt.Font.BOLD));
        jLabel3.setText("Código:");
        jLabel3.setName("jLabel3"); // NOI18N

        codigoTemperaturaText.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        codigoTemperaturaText.setEnabled(false);
        codigoTemperaturaText.setName("codigoTemperaturaText"); // NOI18N

        temperaturaMinimaText.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        temperaturaMinimaText.setEnabled(false);
        temperaturaMinimaText.setName("temperaturaMinimaText"); // NOI18N

        jLabel6.setText("Temperatura Mínima:");
        jLabel6.setName("jLabel6"); // NOI18N

        jLabel8.setText("Descripción:");
        jLabel8.setName("jLabel8"); // NOI18N

        descripcionTemperaturaText.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        descripcionTemperaturaText.setEnabled(false);
        descripcionTemperaturaText.setName("descripcionTemperaturaText"); // NOI18N

        jLabel4.setFont(jLabel4.getFont().deriveFont(jLabel4.getFont().getStyle() & ~java.awt.Font.BOLD));
        jLabel4.setText("Temperatura Tolerancia:");
        jLabel4.setName("jLabel4"); // NOI18N

        jLabel9.setFont(jLabel9.getFont().deriveFont(jLabel9.getFont().getStyle() & ~java.awt.Font.BOLD));
        jLabel9.setText("Temperatura Máxima:");
        jLabel9.setName("jLabel9"); // NOI18N

        temperaturaMaximaText.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        temperaturaMaximaText.setEnabled(false);
        temperaturaMaximaText.setName("temperaturaMaximaText"); // NOI18N

        temperaturaToleranciaText.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        temperaturaToleranciaText.setEnabled(false);
        temperaturaToleranciaText.setName("temperaturaToleranciaText"); // NOI18N

        jLabel10.setText("Grados");
        jLabel10.setName("jLabel10"); // NOI18N

        jLabel11.setText("Grados");
        jLabel11.setName("jLabel11"); // NOI18N

        jLabel12.setText("Grados");
        jLabel12.setName("jLabel12"); // NOI18N

        javax.swing.GroupLayout datosPanel2Layout = new javax.swing.GroupLayout(datosPanel2);
        datosPanel2.setLayout(datosPanel2Layout);
        datosPanel2Layout.setHorizontalGroup(
                datosPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(datosPanel2Layout.createSequentialGroup().addContainerGap().addGroup(datosPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addComponent(jLabel9).addComponent(jLabel3).addComponent(jLabel6).addComponent(jLabel4).addComponent(jLabel8)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(datosPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(datosPanel2Layout.createSequentialGroup().addGroup(datosPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(javax.swing.GroupLayout.Alignment.TRAILING, datosPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false).addComponent(temperaturaMaximaText).addComponent(codigoTemperaturaText, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE).addComponent(temperaturaMinimaText)).addComponent(temperaturaToleranciaText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(datosPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jLabel11).addComponent(jLabel12).addComponent(jLabel10)).addGap(152, 152, 152)).addGroup(datosPanel2Layout.createSequentialGroup().addComponent(descripcionTemperaturaText, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE).addContainerGap()))));
        datosPanel2Layout.setVerticalGroup(
                datosPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(datosPanel2Layout.createSequentialGroup().addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addGroup(datosPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(codigoTemperaturaText, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jLabel3)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(datosPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(descripcionTemperaturaText, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jLabel8)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(datosPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addGroup(datosPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel9).addComponent(temperaturaMaximaText, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)).addComponent(jLabel11)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(datosPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addGroup(datosPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(temperaturaMinimaText, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jLabel6)).addComponent(jLabel10)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(datosPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel4).addComponent(jLabel12).addComponent(temperaturaToleranciaText, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))));

        cerrarTemperaturaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/utn/frm/ui/resources/image/cerrar.png"))); // NOI18N
        cerrarTemperaturaButton.setText("Cerrar");
        cerrarTemperaturaButton.setName("cerrarTemperaturaButton"); // NOI18N
        cerrarTemperaturaButton.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarTemperaturaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout datosDialogTemperaturaLayout = new javax.swing.GroupLayout(datosDialogTemperatura.getContentPane());
        datosDialogTemperatura.getContentPane().setLayout(datosDialogTemperaturaLayout);
        datosDialogTemperaturaLayout.setHorizontalGroup(
                datosDialogTemperaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(datosDialogTemperaturaLayout.createSequentialGroup().addContainerGap().addComponent(datosPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE).addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)).addGroup(javax.swing.GroupLayout.Alignment.TRAILING, datosDialogTemperaturaLayout.createSequentialGroup().addContainerGap(332, Short.MAX_VALUE).addComponent(cerrarTemperaturaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE).addContainerGap()));
        datosDialogTemperaturaLayout.setVerticalGroup(
                datosDialogTemperaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(datosDialogTemperaturaLayout.createSequentialGroup().addContainerGap().addComponent(datosPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(cerrarTemperaturaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE).addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        datosDialogNivel.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        datosDialogNivel.setTitle("Regla  de Control de Nivel");
        datosDialogNivel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        datosDialogNivel.setLocationByPlatform(true);
        datosDialogNivel.setMinimumSize(new java.awt.Dimension(460, 225));
        datosDialogNivel.setModal(true);
        datosDialogNivel.setName("datosDialogNivel"); // NOI18N
        datosDialogNivel.setResizable(false);
        datosDialogNivel.addWindowListener(new java.awt.event.WindowAdapter() {

            public void windowClosed(java.awt.event.WindowEvent evt) {
                datosDialogNivel_windowClosed(evt);
            }
        });

        datosPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Regla de Control de Nivel"));
        datosPanel5.setName("datosPanel5"); // NOI18N

        jLabel15.setFont(jLabel15.getFont().deriveFont(jLabel15.getFont().getStyle() & ~java.awt.Font.BOLD));
        jLabel15.setText("Código:");
        jLabel15.setName("jLabel15"); // NOI18N

        codigoNivelText.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        codigoNivelText.setEnabled(false);
        codigoNivelText.setName("codigoNivelText"); // NOI18N

        nivelMinimoAzucarText.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        nivelMinimoAzucarText.setEnabled(false);
        nivelMinimoAzucarText.setName("nivelMinimoAzucarText"); // NOI18N

        jLabel16.setText("Nivel Mínimo:");
        jLabel16.setName("jLabel16"); // NOI18N

        jLabel17.setText("Descripción:");
        jLabel17.setName("jLabel17"); // NOI18N

        descripcionNivelText.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        descripcionNivelText.setEnabled(false);
        descripcionNivelText.setName("descripcionNivelText"); // NOI18N

        jLabel18.setFont(jLabel18.getFont().deriveFont(jLabel18.getFont().getStyle() & ~java.awt.Font.BOLD));
        jLabel18.setText("Nivel Máximo:");
        jLabel18.setName("jLabel18"); // NOI18N

        nivelMaximoLitrosText.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        nivelMaximoLitrosText.setEnabled(false);
        nivelMaximoLitrosText.setName("nivelMaximoLitrosText"); // NOI18N

        jLabel19.setText("Azúcar");
        jLabel19.setName("jLabel19"); // NOI18N

        jLabel20.setText("Litros");
        jLabel20.setName("jLabel20"); // NOI18N

        javax.swing.GroupLayout datosPanel5Layout = new javax.swing.GroupLayout(datosPanel5);
        datosPanel5.setLayout(datosPanel5Layout);
        datosPanel5Layout.setHorizontalGroup(
                datosPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(datosPanel5Layout.createSequentialGroup().addGap(26, 26, 26).addGroup(datosPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addComponent(jLabel18).addComponent(jLabel15).addComponent(jLabel16).addComponent(jLabel17)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(datosPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(datosPanel5Layout.createSequentialGroup().addGroup(datosPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false).addComponent(nivelMaximoLitrosText).addComponent(codigoNivelText, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE).addComponent(nivelMinimoAzucarText)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(datosPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jLabel19).addComponent(jLabel20))).addComponent(descripcionNivelText, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)).addContainerGap(65, Short.MAX_VALUE)));
        datosPanel5Layout.setVerticalGroup(
                datosPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(datosPanel5Layout.createSequentialGroup().addContainerGap().addGroup(datosPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(codigoNivelText, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jLabel15)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(datosPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(descripcionNivelText, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jLabel17)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addGroup(datosPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel18).addComponent(nivelMaximoLitrosText, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jLabel20)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(datosPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addGroup(datosPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(nivelMinimoAzucarText, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jLabel16)).addComponent(jLabel19)).addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        cerrarNivelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/utn/frm/ui/resources/image/cerrar.png"))); // NOI18N
        cerrarNivelButton.setText("Cerrar");
        cerrarNivelButton.setName("cerrarNivelButton"); // NOI18N
        cerrarNivelButton.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarNivelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout datosDialogNivelLayout = new javax.swing.GroupLayout(datosDialogNivel.getContentPane());
        datosDialogNivel.getContentPane().setLayout(datosDialogNivelLayout);
        datosDialogNivelLayout.setHorizontalGroup(
                datosDialogNivelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(datosDialogNivelLayout.createSequentialGroup().addContainerGap().addGroup(datosDialogNivelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addComponent(cerrarNivelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(datosPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)).addContainerGap(16, Short.MAX_VALUE)));
        datosDialogNivelLayout.setVerticalGroup(
                datosDialogNivelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(datosDialogNivelLayout.createSequentialGroup().addContainerGap().addComponent(datosPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(cerrarNivelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE).addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        datosDialogRemontaje.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        datosDialogRemontaje.setTitle("Regla de Remontaje");
        datosDialogRemontaje.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        datosDialogRemontaje.setLocationByPlatform(true);
        datosDialogRemontaje.setMinimumSize(new java.awt.Dimension(522, 395));
        datosDialogRemontaje.setModal(true);
        datosDialogRemontaje.setName("datosDialogRemontaje"); // NOI18N
        datosDialogRemontaje.setResizable(false);
        datosDialogRemontaje.addWindowListener(new java.awt.event.WindowAdapter() {

            public void windowClosed(java.awt.event.WindowEvent evt) {
                datosDialogRemontaje_windowClosed(evt);
            }
        });

        datosPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Regla de Remontaje"));
        datosPanel.setName("datosPanel"); // NOI18N

        jLabel13.setFont(jLabel13.getFont().deriveFont(jLabel13.getFont().getStyle() & ~java.awt.Font.BOLD));
        jLabel13.setText("Codigo:");
        jLabel13.setName("jLabel13"); // NOI18N

        codigoRemontajeText.setEditable(false);
        codigoRemontajeText.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        codigoRemontajeText.setName("codigoRemontajeText"); // NOI18N

        jLabel14.setText("Descripción:");
        jLabel14.setName("jLabel14"); // NOI18N

        descripcionRemontajeText.setEditable(false);
        descripcionRemontajeText.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        descripcionRemontajeText.setName("descripcionRemontajeText"); // NOI18N

        sPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Remontaje Dia"));
        sPanel1.setName("sPanel1"); // NOI18N

        tablaRemontajeDia.setAutoCreateRowSorter(true);
        tablaRemontajeDia.setModel(model);
        tablaRemontajeDia.setName("tablaRemontajeDia"); // NOI18N
        tablaRemontajeDia.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tablaRemontajeDia.addMouseListener(new java.awt.event.MouseAdapter() {

            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaRemontajeDiaMouseClicked(evt);
            }
        });
        sPanel1.setViewportView(tablaRemontajeDia);

        verRemontajeDiaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/utn/frm/ui/resources/image/ver.png"))); // NOI18N
        verRemontajeDiaButton.setText("Ver");
        verRemontajeDiaButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        verRemontajeDiaButton.setName("verRemontajeDiaButton"); // NOI18N
        verRemontajeDiaButton.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verRemontajeDiaButtonnuevo(evt);
            }
        });

        javax.swing.GroupLayout datosPanelLayout = new javax.swing.GroupLayout(datosPanel);
        datosPanel.setLayout(datosPanelLayout);
        datosPanelLayout.setHorizontalGroup(
                datosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(datosPanelLayout.createSequentialGroup().addGap(24, 24, 24).addGroup(datosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING).addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(datosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(codigoRemontajeText, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(descripcionRemontajeText, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)).addContainerGap(116, Short.MAX_VALUE)).addComponent(sPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE).addGroup(datosPanelLayout.createSequentialGroup().addComponent(verRemontajeDiaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE).addContainerGap()));
        datosPanelLayout.setVerticalGroup(
                datosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(datosPanelLayout.createSequentialGroup().addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addGroup(datosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(codigoRemontajeText, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jLabel13)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(datosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(descripcionRemontajeText, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jLabel14)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(sPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(verRemontajeDiaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE).addGap(31, 31, 31)));

        cerrarRemontajeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/utn/frm/ui/resources/image/cerrar.png"))); // NOI18N
        cerrarRemontajeButton.setText("Cerrar");
        cerrarRemontajeButton.setName("cerrarRemontajeButton"); // NOI18N
        cerrarRemontajeButton.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarRemontajeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout datosDialogRemontajeLayout = new javax.swing.GroupLayout(datosDialogRemontaje.getContentPane());
        datosDialogRemontaje.getContentPane().setLayout(datosDialogRemontajeLayout);
        datosDialogRemontajeLayout.setHorizontalGroup(
                datosDialogRemontajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(datosDialogRemontajeLayout.createSequentialGroup().addGroup(datosDialogRemontajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(datosPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addGroup(javax.swing.GroupLayout.Alignment.TRAILING, datosDialogRemontajeLayout.createSequentialGroup().addContainerGap(422, Short.MAX_VALUE).addComponent(cerrarRemontajeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))).addContainerGap()));
        datosDialogRemontajeLayout.setVerticalGroup(
                datosDialogRemontajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(datosDialogRemontajeLayout.createSequentialGroup().addContainerGap().addComponent(datosPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(cerrarRemontajeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE).addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        datosDialogRemontajeDia.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        datosDialogRemontajeDia.setTitle("Remontaje Dia");
        datosDialogRemontajeDia.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        datosDialogRemontajeDia.setLocationByPlatform(true);
        datosDialogRemontajeDia.setMinimumSize(new java.awt.Dimension(522, 385));
        datosDialogRemontajeDia.setModal(true);
        datosDialogRemontajeDia.setName("datosDialogRemontajeDia"); // NOI18N
        datosDialogRemontajeDia.setResizable(false);
        datosDialogRemontajeDia.addWindowListener(new java.awt.event.WindowAdapter() {

            public void windowClosed(java.awt.event.WindowEvent evt) {
                datosDialogRemontajeDia_windowClosed(evt);
            }
        });

        datosPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Remontaje Dia"));
        datosPanel3.setName("datosPanel3"); // NOI18N

        jLabel21.setFont(jLabel21.getFont().deriveFont(jLabel21.getFont().getStyle() & ~java.awt.Font.BOLD));
        jLabel21.setText("Nombre:");
        jLabel21.setName("jLabel21"); // NOI18N

        nombreRemontajeDiaText.setEditable(false);
        nombreRemontajeDiaText.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        nombreRemontajeDiaText.setName("nombreRemontajeDiaText"); // NOI18N

        sPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Momento Remontaje"));
        sPanel2.setName("sPanel2"); // NOI18N

        tablaMomentoRemontaje.setAutoCreateRowSorter(true);
        tablaMomentoRemontaje.setModel(model);
        tablaMomentoRemontaje.setName("tablaMomentoRemontaje"); // NOI18N
        tablaMomentoRemontaje.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        sPanel2.setViewportView(tablaMomentoRemontaje);

        javax.swing.GroupLayout datosPanel3Layout = new javax.swing.GroupLayout(datosPanel3);
        datosPanel3.setLayout(datosPanel3Layout);
        datosPanel3Layout.setHorizontalGroup(
                datosPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(datosPanel3Layout.createSequentialGroup().addGap(24, 24, 24).addComponent(jLabel21).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(nombreRemontajeDiaText, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE).addContainerGap(268, Short.MAX_VALUE)).addComponent(sPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE));
        datosPanel3Layout.setVerticalGroup(
                datosPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(datosPanel3Layout.createSequentialGroup().addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addGroup(datosPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(nombreRemontajeDiaText, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jLabel21)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(sPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)));

        cerrarRemontajeDiaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/utn/frm/ui/resources/image/cerrar.png"))); // NOI18N
        cerrarRemontajeDiaButton.setText("Cerrar");
        cerrarRemontajeDiaButton.setName("cerrarRemontajeDiaButton"); // NOI18N
        cerrarRemontajeDiaButton.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarRemontajeDiaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout datosDialogRemontajeDiaLayout = new javax.swing.GroupLayout(datosDialogRemontajeDia.getContentPane());
        datosDialogRemontajeDia.getContentPane().setLayout(datosDialogRemontajeDiaLayout);
        datosDialogRemontajeDiaLayout.setHorizontalGroup(
                datosDialogRemontajeDiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(datosDialogRemontajeDiaLayout.createSequentialGroup().addGroup(datosDialogRemontajeDiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(datosPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addGroup(javax.swing.GroupLayout.Alignment.TRAILING, datosDialogRemontajeDiaLayout.createSequentialGroup().addContainerGap(422, Short.MAX_VALUE).addComponent(cerrarRemontajeDiaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))).addContainerGap()));
        datosDialogRemontajeDiaLayout.setVerticalGroup(
                datosDialogRemontajeDiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(datosDialogRemontajeDiaLayout.createSequentialGroup().addContainerGap().addComponent(datosPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(cerrarRemontajeDiaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE).addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        setIconifiable(true);
        setTitle("Regla de Control");

        sPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Reglas de Control"));
        sPanel.setName("sPanel"); // NOI18N

        buscarTabla.setAutoCreateRowSorter(true);
        buscarTabla.setModel(model);
        buscarTabla.setName("buscarTable"); // NOI18N
        buscarTabla.addMouseListener(new java.awt.event.MouseAdapter() {

            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buscarTablaMouseClicked(evt);
            }
        });
        sPanel.setViewportView(buscarTabla);

        salirButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/utn/frm/ui/resources/image/cerrar.png"))); // NOI18N
        salirButton.setText("Cerrar");
        salirButton.setName("salirButton"); // NOI18N
        salirButton.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirButtonActionPerformed(evt);
            }
        });

        buscarCodigoText.setName("buscarCodigoText"); // NOI18N

        jLabel1.setText("Descripción");
        jLabel1.setName("jLabel1"); // NOI18N

        buscarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/utn/frm/ui/resources/image/buscar.png"))); // NOI18N
        buscarButton.setText("Buscar");
        buscarButton.setName("buscarButton"); // NOI18N
        buscarButton.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarButtonActionPerformed(evt);
            }
        });

        limpiarBuscadorButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/utn/frm/ui/resources/image/limpiar.png"))); // NOI18N
        limpiarBuscadorButton.setText("Limpiar");
        limpiarBuscadorButton.setName("limpiarBuscarButton"); // NOI18N
        limpiarBuscadorButton.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarBuscadorButtonActionPerformed(evt);
            }
        });

        nuevoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/utn/frm/ui/resources/image/agregar.png"))); // NOI18N
        nuevoButton.setText("Nuevo");
        nuevoButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        nuevoButton.setName("nuevoButton"); // NOI18N
        nuevoButton.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevo(evt);
            }
        });

        editarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/utn/frm/ui/resources/image/editar.png"))); // NOI18N
        editarButton.setText("Editar");
        editarButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        editarButton.setName("editarButton"); // NOI18N
        editarButton.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarButtonnuevo(evt);
            }
        });

        buscarDescripcionText.setName("buscarDescripcionText"); // NOI18N

        jLabel5.setText("Código");
        jLabel5.setName("jLabel5"); // NOI18N

        copiarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/utn/frm/ui/resources/image/copiar.png"))); // NOI18N
        copiarButton.setText("Copiar");
        copiarButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        copiarButton.setMaximumSize(new java.awt.Dimension(31, 17));
        copiarButton.setMinimumSize(new java.awt.Dimension(31, 17));
        copiarButton.setName("copiarButton"); // NOI18N
        copiarButton.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copiarButtonActionPerformed(evt);
            }
        });

        generarInformeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/utn/frm/ui/resources/image/informe.png"))); // NOI18N
        generarInformeButton.setText("Generar Informe");
        generarInformeButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        generarInformeButton.setName("generarInformeButton"); // NOI18N
        generarInformeButton.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarInformeButton(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addContainerGap().addComponent(sPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE)).addGroup(layout.createSequentialGroup().addContainerGap().addComponent(nuevoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(editarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(copiarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(generarInformeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE).addComponent(salirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)).addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup().addGap(13, 13, 13).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(buscarCodigoText, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jLabel5)).addGap(10, 10, 10).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(buscarDescripcionText, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jLabel1)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(buscarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE).addComponent(limpiarBuscadorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))).addContainerGap()));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup().addGap(40, 40, 40).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addGroup(layout.createSequentialGroup().addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel1).addComponent(jLabel5)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(buscarCodigoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(buscarDescripcionText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))).addComponent(limpiarBuscadorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(buscarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(sPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(nuevoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(salirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(editarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(copiarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(generarInformeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)).addContainerGap()));

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nuevo(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevo
        nuevo();
    }//GEN-LAST:event_nuevo

    private void buscarTablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarTablaMouseClicked
        if (evt.getClickCount() > 1) {
            editar();
        }
    }//GEN-LAST:event_buscarTablaMouseClicked

    private void salirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirButtonActionPerformed
        dispose();
    }//GEN-LAST:event_salirButtonActionPerformed

    private void guardar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardar
        guardar();
    }//GEN-LAST:event_guardar

    private void eliminar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminar

        eliminar();
    }//GEN-LAST:event_eliminar

    private void buscarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarButtonActionPerformed
        gestorAbm.getFilter().setCodigo(buscarCodigoText.getText());
        gestorAbm.getFilter().setDescripcion(buscarDescripcionText.getText());
        model.setRows(gestorAbm.buscar());
    }//GEN-LAST:event_buscarButtonActionPerformed

    private void limpiarBuscadorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarBuscadorButtonActionPerformed
        buscarCodigoText.setText("");
        buscarDescripcionText.setText("");
        gestorAbm.getFilter().clear();
    }//GEN-LAST:event_limpiarBuscadorButtonActionPerformed

    private void limpiarDatosEntityButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarDatosEntityButtonActionPerformed
        codigoText.setText("");
        descripcionText.setText("");
    }//GEN-LAST:event_limpiarDatosEntityButtonActionPerformed

    private void cerrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarButtonActionPerformed
        cerrar();
    }//GEN-LAST:event_cerrarButtonActionPerformed

    private void datosDialog_windowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_datosDialog_windowClosed
        cerrar();
    }//GEN-LAST:event_datosDialog_windowClosed

    private void editarButtonnuevo(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarButtonnuevo
        editar();
    }//GEN-LAST:event_editarButtonnuevo

    private void cerrarTemperaturaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarTemperaturaButtonActionPerformed
        cerrarTemperatura();
    }//GEN-LAST:event_cerrarTemperaturaButtonActionPerformed

    private void datosDialogTemperatura_windowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_datosDialogTemperatura_windowClosed
        cerrarTemperatura();
    }//GEN-LAST:event_datosDialogTemperatura_windowClosed

    private void cerrarNivelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarNivelButtonActionPerformed
        cerrarNivel();
    }//GEN-LAST:event_cerrarNivelButtonActionPerformed

    private void datosDialogNivel_windowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_datosDialogNivel_windowClosed
        cerrarNivel();
    }//GEN-LAST:event_datosDialogNivel_windowClosed

    private void verTemperaturaButton(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verTemperaturaButton
        ReglaControlTemperatura reglaControlTemperatura = modelTemperatura.getSelectedEntity();
        if (reglaControlTemperatura != null) {
            bindingTemperatura(reglaControlTemperatura);
            showDatosDialogTemperatura(true);
        }
    }//GEN-LAST:event_verTemperaturaButton

    private void verNivelButton(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verNivelButton
        ReglaControlNivel reglaControlNivel = modelNivel.getSelectedEntity();
        if (reglaControlNivel != null) {
            bindingNivel(reglaControlNivel);
            showDatosDialogNivel(true);
        }
    }//GEN-LAST:event_verNivelButton

    private void verRemontajeButton(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verRemontajeButton
        ReglaControlRemontaje reglaControlRemontaje = modelRemontaje.getSelectedEntity();
        if (reglaControlRemontaje != null) {
            bindingRemontaje(reglaControlRemontaje);
            showDatosDialogRemontaje(true);
        }
    }//GEN-LAST:event_verRemontajeButton

    private void temperaturaComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_temperaturaComboBoxItemStateChanged
        verTemperaturaButton.setEnabled(modelTemperatura.getSelectedEntity() != null);
    }//GEN-LAST:event_temperaturaComboBoxItemStateChanged

    private void nivelComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_nivelComboBoxItemStateChanged
        verNivelButton.setEnabled(modelNivel.getSelectedEntity() != null);
    }//GEN-LAST:event_nivelComboBoxItemStateChanged

    private void remontajeComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_remontajeComboBoxItemStateChanged
        verRemontajeButton.setEnabled(modelRemontaje.getSelectedEntity() != null);
    }//GEN-LAST:event_remontajeComboBoxItemStateChanged

    private void tablaRemontajeDiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaRemontajeDiaMouseClicked
        if (evt.getClickCount() > 1) {
            verReglaRemontajeDia();
        }
    }//GEN-LAST:event_tablaRemontajeDiaMouseClicked

    private void verRemontajeDiaButtonnuevo(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verRemontajeDiaButtonnuevo
        verReglaRemontajeDia();
    }//GEN-LAST:event_verRemontajeDiaButtonnuevo

    private void cerrarRemontajeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarRemontajeButtonActionPerformed
        cerrarRemontaje();
    }//GEN-LAST:event_cerrarRemontajeButtonActionPerformed

    private void datosDialogRemontaje_windowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_datosDialogRemontaje_windowClosed
        cerrarRemontaje();
    }//GEN-LAST:event_datosDialogRemontaje_windowClosed

    private void cerrarRemontajeDiaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarRemontajeDiaButtonActionPerformed
        cerrarRemontajeDia();
    }//GEN-LAST:event_cerrarRemontajeDiaButtonActionPerformed

    private void datosDialogRemontajeDia_windowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_datosDialogRemontajeDia_windowClosed
        cerrarRemontajeDia();
    }//GEN-LAST:event_datosDialogRemontajeDia_windowClosed

    private void copiarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copiarButtonActionPerformed
        copiar();
    }//GEN-LAST:event_copiarButtonActionPerformed

    private void generarInformeButton(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarInformeButton
        try {
            gestorAbm.ejecutarReporte();
        } catch (ReporteException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error al generar el reporte", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_generarInformeButton
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarButton;
    private javax.swing.JTextField buscarCodigoText;
    private javax.swing.JTextField buscarDescripcionText;
    private javax.swing.JTable buscarTabla;
    private javax.swing.JButton cerrarButton;
    private javax.swing.JButton cerrarNivelButton;
    private javax.swing.JButton cerrarRemontajeButton;
    private javax.swing.JButton cerrarRemontajeDiaButton;
    private javax.swing.JButton cerrarTemperaturaButton;
    private javax.swing.JTextField codigoNivelText;
    private javax.swing.JTextField codigoRemontajeText;
    private javax.swing.JTextField codigoTemperaturaText;
    private javax.swing.JTextField codigoText;
    private javax.swing.JButton copiarButton;
    private javax.swing.JDialog datosDialog;
    private javax.swing.JDialog datosDialogNivel;
    private javax.swing.JDialog datosDialogRemontaje;
    private javax.swing.JDialog datosDialogRemontajeDia;
    private javax.swing.JDialog datosDialogTemperatura;
    private javax.swing.JPanel datosPanel;
    private javax.swing.JPanel datosPanel1;
    private javax.swing.JPanel datosPanel2;
    private javax.swing.JPanel datosPanel3;
    private javax.swing.JPanel datosPanel5;
    private javax.swing.JTextField descripcionNivelText;
    private javax.swing.JTextField descripcionRemontajeText;
    private javax.swing.JTextField descripcionTemperaturaText;
    private javax.swing.JTextField descripcionText;
    private javax.swing.JButton editarButton;
    private javax.swing.JButton eliminarButton;
    private javax.swing.JButton generarInformeButton;
    private javax.swing.JButton guardarButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton limpiarBuscadorButton;
    private javax.swing.JButton limpiarDatosEntityButton;
    private javax.swing.JComboBox nivelComboBox;
    private javax.swing.JTextField nivelMaximoLitrosText;
    private javax.swing.JTextField nivelMinimoAzucarText;
    private javax.swing.JTextField nombreRemontajeDiaText;
    private javax.swing.JButton nuevoButton;
    private javax.swing.JComboBox remontajeComboBox;
    private javax.swing.JScrollPane sPanel;
    private javax.swing.JScrollPane sPanel1;
    private javax.swing.JScrollPane sPanel2;
    private javax.swing.JButton salirButton;
    private javax.swing.JTable tablaMomentoRemontaje;
    private javax.swing.JTable tablaRemontajeDia;
    private javax.swing.JComboBox temperaturaComboBox;
    private javax.swing.JTextField temperaturaMaximaText;
    private javax.swing.JTextField temperaturaMinimaText;
    private javax.swing.JTextField temperaturaToleranciaText;
    private javax.swing.JButton verNivelButton;
    private javax.swing.JButton verRemontajeButton;
    private javax.swing.JButton verRemontajeDiaButton;
    private javax.swing.JButton verTemperaturaButton;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    private void cerrar() {
        reset();
        showDatosDialog(false);
    }

    private void cerrarTemperatura() {
        resetTemperatura();
        showDatosDialogTemperatura(false);
    }

    private void cerrarNivel() {
        resetNivel();
        showDatosDialogNivel(false);
    }

    private void cerrarRemontaje() {
        resetRemontaje();
        showDatosDialogRemontaje(false);
    }

    private void cerrarRemontajeDia() {
        resetRemontajeDia();
        showDatosDialogRemontajeDia(false);
    }

    private void nuevo() {
        gestorAbm.nuevo();
        bindinDataEntity(servidor);
        habilitarPanelDatos(true);
        eliminarButton.setEnabled(false);
        showDatosDialog(true);
    }

    private void editar() {
        ReglaControl reglaControl = null;

        if (buscarTabla.getSelectedRow() != -1) {
            reglaControl = model.getRow(buscarTabla.getSelectedRow());
            if (reglaControl != null) {
                gestorAbm.setEntity(reglaControl);
                bindinDataEntity(servidor);
                habilitarPanelDatos(true);
                showDatosDialog(true);
            }
        }
        if (reglaControl == null) {
            JOptionPane.showInternalMessageDialog(this, "Debe seleccionar una Regla de Control para editar");
        }
    }

    private void copiar() {
        ReglaControl reglaControl = null;

        if (buscarTabla.getSelectedRow() != -1) {
            reglaControl = model.getRow(buscarTabla.getSelectedRow());
            if (reglaControl != null) {
                gestorAbm.setEntity(reglaControl);
                try {
                    gestorAbm.copiar();
                    reset();
                    JOptionPane.showMessageDialog(this, "Se ha copiado exitosamente", "Información", JOptionPane.INFORMATION_MESSAGE);
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, ex.getMessage());
                }
            }
        }
        if (reglaControl == null) {
            JOptionPane.showInternalMessageDialog(this, "Debe seleccionar una Regla de Control para copiar");
        }
    }

    private void guardar() {

        bindinDataEntity(cliente);
        try {
            gestorAbm.valid();
            gestorAbm.guardar();
            reset();
            showDatosDialog(false);
        } catch (ValidateException ex) {
            JOptionPane.showMessageDialog(datosDialog, ex.getMessage());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(datosDialog, ex.getMessage());
        }
    }

    private void showDatosDialog(boolean show) {
        if (show) {
            Utiles.centrarFormulario(datosDialog);
        }
        datosDialog.setVisible(show);
    }

    private void showDatosDialogTemperatura(boolean show) {
        if (show) {
            Utiles.centrarFormulario(datosDialogTemperatura);
        }
        datosDialogTemperatura.setVisible(show);
    }

    private void showDatosDialogNivel(boolean show) {
        if (show) {
            Utiles.centrarFormulario(datosDialogNivel);
        }
        datosDialogNivel.setVisible(show);
    }

    private void showDatosDialogRemontaje(boolean show) {
        if (show) {
            Utiles.centrarFormulario(datosDialogRemontaje);
        }
        datosDialogRemontaje.setVisible(show);
    }

    private void showDatosDialogRemontajeDia(boolean show) {
        if (show) {
            Utiles.centrarFormulario(datosDialogRemontajeDia);
        }
        datosDialogRemontajeDia.setVisible(show);
    }

    private void verReglaRemontajeDia() {
        int index = tablaRemontajeDia.getSelectedRow();
        if (index >= 0) {
            RemontajeDia reglaRemontajeDia = modelRemontajeDia.getRow(index);
            if (reglaRemontajeDia != null) {
                bindingRemontajeDia(reglaRemontajeDia);
                showDatosDialogRemontajeDia(true);
            }
        } else {
            JOptionPane.showInternalMessageDialog(this, "Debe seleccionar un Remontaje Dia para eliminar");
        }
    }

    private void eliminar() {
        ReglaControl reglaControl = null;

        try {
            if (buscarTabla.getSelectedRow() != -1) {
                reglaControl = model.getRow(buscarTabla.getSelectedRow());
                if (reglaControl != null) {

                    int respuesta = JOptionPane.showConfirmDialog(datosDialog, "Está seguro que desea eliminar la Regla de Control seleccionado?",
                            "Confirmar Eliminación", JOptionPane.OK_CANCEL_OPTION);

                    if (respuesta == JOptionPane.OK_OPTION) {
                        gestorAbm.setEntity(reglaControl);
                        gestorAbm.eliminar();
                        reset();
                        showDatosDialog(false);
                    }
                }
            }
            if (reglaControl == null) {
                JOptionPane.showInternalMessageDialog(this, "Debe seleccionar una Regla de Control para eliminar");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }

    private void reset() {
        codigoText.setText("");
        descripcionText.setText("");
        setEntity(null);
        habilitarPanelDatos(false);
        model.setRows(gestorAbm.buscar());
    }

    private void resetTemperatura() {
        temperaturaMaximaText.setText("");
        temperaturaMinimaText.setText("");
        temperaturaToleranciaText.setText("");
        codigoTemperaturaText.setText("");
        descripcionTemperaturaText.setText("");
    }

    private void resetNivel() {
        codigoNivelText.setText("");
        descripcionNivelText.setText("");
        nivelMaximoLitrosText.setText("");
        nivelMinimoAzucarText.setText("");
    }

    private void resetRemontaje() {
        codigoRemontajeText.setText("");
        descripcionRemontajeText.setText("");
    }

    private void resetRemontajeDia() {
        nombreRemontajeDiaText.setText("");
    }

    private void bindingTemperatura(ReglaControlTemperatura reglaControlTemperatura) {
        temperaturaMaximaText.setText(reglaControlTemperatura.getTemperaturaMaxima().toString());
        temperaturaMinimaText.setText(reglaControlTemperatura.getTemperaturaMinima().toString());
        temperaturaToleranciaText.setText(reglaControlTemperatura.getTemperaturaTolerancia().toString());
        codigoTemperaturaText.setText(reglaControlTemperatura.getCodigo());
        descripcionTemperaturaText.setText(reglaControlTemperatura.getDescripcion());
    }

    private void bindingNivel(ReglaControlNivel reglaControlNivel) {
        codigoNivelText.setText(reglaControlNivel.getCodigo());
        descripcionNivelText.setText(reglaControlNivel.getDescripcion());
        nivelMaximoLitrosText.setText(reglaControlNivel.getNivelMaximoCapacidad().toString());
        nivelMinimoAzucarText.setText(reglaControlNivel.getNivelMinimoAzucar().toString());
    }

    private void bindingRemontaje(ReglaControlRemontaje reglaControlRemontaje) {
        codigoRemontajeText.setText(reglaControlRemontaje.getCodigo());
        descripcionRemontajeText.setText(reglaControlRemontaje.getDescripcion());
        modelRemontajeDia.setRows(reglaControlRemontaje.getRemontajesDia());
    }

    private void bindingRemontajeDia(RemontajeDia remontajeDia) {
        nombreRemontajeDiaText.setText(remontajeDia.getNombre());
        modelMomentoRemontaje.setRows(remontajeDia.getMomentosRemontajes());
    }

    public ReglaControlAbm getGestorAbm() {
        return gestorAbm;
    }

    public void setGestorAbm(ReglaControlAbm gestorAbm) {
        this.gestorAbm = gestorAbm;
    }

    public ReglaControl getEntity() {
        return gestorAbm.getEntity();
    }

    public ReglaControlTemperatura getReglaTemperatura() {
        return getEntity().getReglaControlTemperatura();
    }

    public ReglaControlNivel getReglaNivel() {
        return getEntity().getReglaControlNivel();
    }

    public ReglaControlRemontaje getReglaRemontaje() {
        return getEntity().getReglaControlRemontaje();
    }

    public void setEntity(ReglaControl entity) {
        this.gestorAbm.setEntity(entity);
    }

    private void habilitarPanelDatos(boolean habilitar) {
        codigoText.setEnabled(habilitar);
        descripcionText.setEnabled(habilitar);
        cerrarButton.setEnabled(habilitar);
        guardarButton.setEnabled(habilitar);
        eliminarButton.setEnabled(habilitar);
        limpiarDatosEntityButton.setEnabled(habilitar);
        nuevoButton.setEnabled(true);
    }
    private final int cliente = 0;
    private final int servidor = 1;

    public void bindinDataEntity(int fuente) {
        if (fuente == servidor) {
            codigoText.setText(getEntity().getCodigo());
            descripcionText.setText(getEntity().getDescripcion());
            modelTemperatura.setSelectedEntity(getEntity().getReglaControlTemperatura());
            if (getReglaTemperatura() == null) {
                verTemperaturaButton.setEnabled(false);
            } else {
                verTemperaturaButton.setEnabled(true);
            }
            modelNivel.setSelectedEntity(getEntity().getReglaControlNivel());
            if (getReglaNivel() == null) {
                verNivelButton.setEnabled(false);
            } else {
                verNivelButton.setEnabled(true);
            }
            modelRemontaje.setSelectedEntity(getEntity().getReglaControlRemontaje());
            if (getReglaRemontaje() == null) {
                verRemontajeButton.setEnabled(false);
            } else {
                verRemontajeButton.setEnabled(true);
            }
        } else if (fuente == cliente) {
            getEntity().setCodigo(codigoText.getText());
            getEntity().setDescripcion(descripcionText.getText());
            getEntity().setReglaControlTemperatura(modelTemperatura.getSelectedEntity());
            getEntity().setReglaControlNivel(modelNivel.getSelectedEntity());
            getEntity().setReglaControlRemontaje(modelRemontaje.getSelectedEntity());
        }

    }

    public List<ReglaControlTemperatura> buscarTodosReglaTemperatura() {
        List<ReglaControlTemperatura> list = gestorAbm.buscarTodosReglaTemperatura();
        if (list.size() == 0) {
            verTemperaturaButton.setEnabled(false);
        }
        return list;
    }

    public List<ReglaControlNivel> buscarTodosReglaNivel() {
        List<ReglaControlNivel> list = gestorAbm.buscarTodosReglaNivel();
        if (list.size() == 0) {
            verNivelButton.setEnabled(false);
        }
        return list;
    }

    public List<ReglaControlRemontaje> buscarTodosReglaRemontaje() {
        List<ReglaControlRemontaje> list = gestorAbm.buscarTodosReglaRemontaje();
        if (list.size() == 0) {
            verRemontajeButton.setEnabled(false);
        }
        return list;
    }
}
